name: cabal-cache-native
description: Native, granular cache for Haskell cabal projects
inputs:
  project-path:
    description: Relative path to the cabal project
    default: .
    required: false
  plan-json:
    description: Relative path to cabal's plan.json file
    required: false
    default: dist-newstyle/cache/plan.json
  store-path:
    description: Path to the cabal store
    required: true
  cache-key-prefix:
    description: Extra string to prepended to the cache keys. It can be used to isolate different caches or start from scratch.
    required: false
    default: cabal-
  ghc:
    description: Path to ghc
    required: false
    default: ghc
  ghcPkg:
    description: Path to ghc-pkg
    required: false
    default: ghc-pkg

runs:
  using: node20
  main: ./dist/restore.js
  post: ./dist/save.js
