name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  cache-epoch: test-${{ github.run_id }}-${{ github.run_attempt || 0 }}

jobs:
  basic-validation:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run prettier
        run: npm run format-check

      - name: Build
        run: npm run build

      - name: Compare the expected and actual dist directories
        run: |
          if [ "$(git diff --ignore-space-at-eol ./dist | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after the build. See the status below:"
            git diff
            exit 1
          fi
        id: diff

      # If inners of the dist directory were different than expected, upload the expected version as an artifact
      - name: Upload artifact
        if: ${{failure() && steps.diff.conclusion == 'failure'}}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Audit packages
        run: npm audit --audit-level=high

  cache-test-cabal-3-10:
    needs: basic-validation
    uses: ./.github/workflows/test-workflow.yml
    with:
      runs-on: ubuntu-latest
      ghc-version: 9.8.2
      cabal-version: 3.10.3.0
      package-id: lens
      index-state: "2024-07-04T00:00:00Z"

  cache-test-cabal-3-12:
    needs: basic-validation
    uses: ./.github/workflows/test-workflow.yml
    with:
      runs-on: ubuntu-latest
      ghc-version: 9.8.2
      cabal-version: 3.12.1.0
      package-id: lens
      index-state: "2024-07-04T00:00:00Z"
