name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  cache-epoch: test-${{ github.run_id }}-${{ github.run_attempt || 0 }}

jobs:
  basic-validation:
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main
    with:
      node-version: "20.x"
      operating-systems: |
        ["ubuntu-latest"]

  check-dist:
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@main
    with:
      node-version: "20.x"

  cache-test:
    needs: check-dist
    uses: ./.github/workflows/test-workflow.yml
    with:
      ghc-version: 9.4.8
      cabal-version: 3.10.3.0
      build-command: cabal build cabal-plan
      cabal-project: |
        index-state: 2024-07-04T00:00:00Z
        extra-packages: cabal-plan
