name: Basic validation

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  cache-epoch: test-${{ github.run_id }}-${{ github.run_attempt || 0 }}

jobs:
  basic-validation:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run prettier
        run: npm run format-check

      - name: Build
        run: npm run build

      - name: Compare the expected and actual dist directories
        run: git diff --ignore-space-at-eol --exit-code --name-status ./dist
        id: diff

      # If inners of the dist directory were different than expected, upload the expected version as an artifact
      - name: Upload artifact
        if: ${{failure() && steps.diff.conclusion == 'failure'}}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Audit packages
        run: npm audit --audit-level=high

  tests:
    needs: basic-validation
    uses: ./.github/workflows/tests.yml
