name: Test build

on:
  workflow_call:
    inputs:
      ghc-version:
        description: The version of GHC to use
        type: string
      cabal-version:
        description: The version of cabal-install to use
        type: string
      package-id:
        type: string
      index-state:
        type: string
      extra-cache-key:
        type: string
      runs-on:
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          path: cabal-cache-native

      - uses: actions/cache@v4
        with:
          # NOTE: I wish haskell-actions/setup would tell us this location
          # (perhaps even better if cabal itself would tell us)
          path: /home/runner/.cabal/packages/hackage.haskell.org/01-index.*
          key: cache-test-hackage-index
          save-always: true

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ inputs.ghc-version }}
          cabal-version: ${{ inputs.cabal-version }}

      - run: |
          mkdir test-project
          echo "index-state: ${{ inputs.index-state }}" >> test-project/cabal.project
          echo "extra-packages: ${{ inputs.package-id }}" >> test-project/cabal.project

      - run: cabal build ${{ inputs.package-id }} --dry-run
        working-directory: test-project

      - uses: ./cabal-cache-native
        with:
          store-path: ${{ steps.setup.outputs.cabal-store }}
          project-path: test-project
          extra-cache-key: ${{ inputs.extra-cache-key }}

      - run: cabal build ${{ inputs.package-id }}
        working-directory: test-project
