name: Integration tests

on: workflow_call

permissions:
  contents: read

env:
  cache-epoch: test-${{ github.run_id }}-${{ github.run_attempt || 0 }}

jobs:
  # cache-test-cabal-3-10:
  #   uses: ./.github/workflows/test-workflow.yml
  #   with:
  #     ghc-version: 9.8.2
  #     cabal-version: 3.10.3.0
  #     package-id: lens
  #     index-state: "2024-07-04T00:00:00Z"

  cache-test-cabal-3-12:
    uses: ./.github/workflows/test-workflow.yml
    with:
      ghc-version: 9.8.2
      cabal-version: 3.12.1.0
      package-id: lens
      index-state: "2024-07-04T00:00:00Z"
